# Tell pnpm which directories are part of this workspace
packages:
  - "." # include the root package
  # - 'packages/*'     # uncomment if you have a packages/ subfolder

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp
  - unrs-resolver
